version: '3.9'
name: spa
services:
    mysql:
        image: mysql:latest
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
            - ./.docker/mysql:/var/lib/mysql
