import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { TRPCReactProvider } from "~/trpc/react";

import "~/styles/globals.css";
import { Navbar } from "./Navbar";

export const metadata: Metadata = {
    title: "SPA",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${GeistSans.variable} dark`}>
            <body className="min-h-screen">
                <div className="flex min-h-screen w-full max-sm:flex-col">
                    <TRPCReactProvider>
                        <Navbar />
                        <main className="w-full">{children}</main>
                    </TRPCReactProvider>
                </div>
            </body>
        </html>
    );
}

