query getTaskPages {
    getAllTaskPages {
        id
        name
        isBookmarked
        colorClass
        taskGroups {
            id
            name
            tasks {
                id
                title
                color
                deadline
                subtasks {
                    id
                    isCompleted
                    title
                }
                tags {
                    id
                    title
                    color
                }
            }
        }
    }
}
